/*
Alertmanager API

API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alertmanagerapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Alert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Alert{}

// Alert struct for Alert
type Alert struct {
	Labels map[string]string `json:"labels"`
	GeneratorURL *string `json:"generatorURL,omitempty"`
}

type _Alert Alert

// NewAlert instantiates a new Alert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlert(labels map[string]string) *Alert {
	this := Alert{}
	this.Labels = labels
	return &this
}

// NewAlertWithDefaults instantiates a new Alert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertWithDefaults() *Alert {
	this := Alert{}
	return &this
}

// GetLabels returns the Labels field value
func (o *Alert) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *Alert) GetLabelsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *Alert) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetGeneratorURL returns the GeneratorURL field value if set, zero value otherwise.
func (o *Alert) GetGeneratorURL() string {
	if o == nil || IsNil(o.GeneratorURL) {
		var ret string
		return ret
	}
	return *o.GeneratorURL
}

// GetGeneratorURLOk returns a tuple with the GeneratorURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetGeneratorURLOk() (*string, bool) {
	if o == nil || IsNil(o.GeneratorURL) {
		return nil, false
	}
	return o.GeneratorURL, true
}

// HasGeneratorURL returns a boolean if a field has been set.
func (o *Alert) HasGeneratorURL() bool {
	if o != nil && !IsNil(o.GeneratorURL) {
		return true
	}

	return false
}

// SetGeneratorURL gets a reference to the given string and assigns it to the GeneratorURL field.
func (o *Alert) SetGeneratorURL(v string) {
	o.GeneratorURL = &v
}

func (o Alert) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Alert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["labels"] = o.Labels
	if !IsNil(o.GeneratorURL) {
		toSerialize["generatorURL"] = o.GeneratorURL
	}
	return toSerialize, nil
}

func (o *Alert) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlert := _Alert{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlert)

	if err != nil {
		return err
	}

	*o = Alert(varAlert)

	return err
}

type NullableAlert struct {
	value *Alert
	isSet bool
}

func (v NullableAlert) Get() *Alert {
	return v.value
}

func (v *NullableAlert) Set(val *Alert) {
	v.value = val
	v.isSet = true
}

func (v NullableAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlert(val *Alert) *NullableAlert {
	return &NullableAlert{value: val, isSet: true}
}

func (v NullableAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


