/*
Alertmanager API

API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alertmanagerapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Silence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Silence{}

// Silence struct for Silence
type Silence struct {
	Matchers []Matcher `json:"matchers"`
	StartsAt time.Time `json:"startsAt"`
	EndsAt time.Time `json:"endsAt"`
	CreatedBy string `json:"createdBy"`
	Comment string `json:"comment"`
}

type _Silence Silence

// NewSilence instantiates a new Silence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSilence(matchers []Matcher, startsAt time.Time, endsAt time.Time, createdBy string, comment string) *Silence {
	this := Silence{}
	this.Matchers = matchers
	this.StartsAt = startsAt
	this.EndsAt = endsAt
	this.CreatedBy = createdBy
	this.Comment = comment
	return &this
}

// NewSilenceWithDefaults instantiates a new Silence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSilenceWithDefaults() *Silence {
	this := Silence{}
	return &this
}

// GetMatchers returns the Matchers field value
func (o *Silence) GetMatchers() []Matcher {
	if o == nil {
		var ret []Matcher
		return ret
	}

	return o.Matchers
}

// GetMatchersOk returns a tuple with the Matchers field value
// and a boolean to check if the value has been set.
func (o *Silence) GetMatchersOk() ([]Matcher, bool) {
	if o == nil {
		return nil, false
	}
	return o.Matchers, true
}

// SetMatchers sets field value
func (o *Silence) SetMatchers(v []Matcher) {
	o.Matchers = v
}

// GetStartsAt returns the StartsAt field value
func (o *Silence) GetStartsAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartsAt
}

// GetStartsAtOk returns a tuple with the StartsAt field value
// and a boolean to check if the value has been set.
func (o *Silence) GetStartsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartsAt, true
}

// SetStartsAt sets field value
func (o *Silence) SetStartsAt(v time.Time) {
	o.StartsAt = v
}

// GetEndsAt returns the EndsAt field value
func (o *Silence) GetEndsAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndsAt
}

// GetEndsAtOk returns a tuple with the EndsAt field value
// and a boolean to check if the value has been set.
func (o *Silence) GetEndsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndsAt, true
}

// SetEndsAt sets field value
func (o *Silence) SetEndsAt(v time.Time) {
	o.EndsAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *Silence) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *Silence) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *Silence) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetComment returns the Comment field value
func (o *Silence) GetComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Comment
}

// GetCommentOk returns a tuple with the Comment field value
// and a boolean to check if the value has been set.
func (o *Silence) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comment, true
}

// SetComment sets field value
func (o *Silence) SetComment(v string) {
	o.Comment = v
}

func (o Silence) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Silence) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["matchers"] = o.Matchers
	toSerialize["startsAt"] = o.StartsAt
	toSerialize["endsAt"] = o.EndsAt
	toSerialize["createdBy"] = o.CreatedBy
	toSerialize["comment"] = o.Comment
	return toSerialize, nil
}

func (o *Silence) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"matchers",
		"startsAt",
		"endsAt",
		"createdBy",
		"comment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSilence := _Silence{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSilence)

	if err != nil {
		return err
	}

	*o = Silence(varSilence)

	return err
}

type NullableSilence struct {
	value *Silence
	isSet bool
}

func (v NullableSilence) Get() *Silence {
	return v.value
}

func (v *NullableSilence) Set(val *Silence) {
	v.value = val
	v.isSet = true
}

func (v NullableSilence) IsSet() bool {
	return v.isSet
}

func (v *NullableSilence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSilence(val *Silence) *NullableSilence {
	return &NullableSilence{value: val, isSet: true}
}

func (v NullableSilence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSilence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


