/*
Alertmanager API

API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alertmanagerapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PeerStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerStatus{}

// PeerStatus struct for PeerStatus
type PeerStatus struct {
	Name string `json:"name"`
	Address string `json:"address"`
}

type _PeerStatus PeerStatus

// NewPeerStatus instantiates a new PeerStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerStatus(name string, address string) *PeerStatus {
	this := PeerStatus{}
	this.Name = name
	this.Address = address
	return &this
}

// NewPeerStatusWithDefaults instantiates a new PeerStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerStatusWithDefaults() *PeerStatus {
	this := PeerStatus{}
	return &this
}

// GetName returns the Name field value
func (o *PeerStatus) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PeerStatus) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PeerStatus) SetName(v string) {
	o.Name = v
}

// GetAddress returns the Address field value
func (o *PeerStatus) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *PeerStatus) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *PeerStatus) SetAddress(v string) {
	o.Address = v
}

func (o PeerStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *PeerStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerStatus := _PeerStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPeerStatus)

	if err != nil {
		return err
	}

	*o = PeerStatus(varPeerStatus)

	return err
}

type NullablePeerStatus struct {
	value *PeerStatus
	isSet bool
}

func (v NullablePeerStatus) Get() *PeerStatus {
	return v.value
}

func (v *NullablePeerStatus) Set(val *PeerStatus) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerStatus) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerStatus(val *PeerStatus) *NullablePeerStatus {
	return &NullablePeerStatus{value: val, isSet: true}
}

func (v NullablePeerStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


