apiVersion: alertmanager.prometheus.io.alertmanager.prometheus.io/v1alpha1
kind: Silence
metadata:
  labels:
    app.kubernetes.io/name: alert-operator
    app.kubernetes.io/managed-by: kustomize
  name: silence-sample
spec:
  # TODO(user): Add fields here
